services:
  backend:
    image: ${DOCKER_USERNAME:-drawlink}/${BACKEND_IMAGE:-backend}:latest
    container_name: drawlink-backend
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    networks:
      - global-network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always

  frontend:
    image: ${DOCKER_USERNAME:-drawlink}/${FRONTEND_IMAGE:-frontend}:latest
    container_name: drawlink-frontend
    depends_on:
      - backend
    networks:
      - global-network
    restart: always

networks:
  global-network:
    external: true